name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # De actie wordt geactiveerd wanneer er naar de 'main' branch gepusht wordt

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Checkout de code
      - name: Checkout code
        uses: actions/checkout@v2

      # Stap 2: Stel SSH in voor GitHub Pages deployment
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # Stap 3: Stel de achtergrondkleur in vanuit de GitHub Secrets
      - name: Set background color from secret
        run: echo "BACKGROUND_COLOR=${{ secrets.PRODUCTION_BG_COLOR }}" >> $GITHUB_ENV

      # Stap 4: Deploy naar GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}  # Gebruik de SSH private key voor authenticatie
          publish_dir: ./  # Publiceer de root directory of je public map (bijv. ./build)
          user_name: 'GitHub Actions'
          user_email: 'actions@github.com'
