name: Deploy to Production

on:
  push:
    branches:
      - main  # Alleen wanneer er naar de main branch gepusht wordt

jobs:
  build:
    runs-on: ubuntu-latest  # Gebruik een Ubuntu machine voor de build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set background color from secret
        run: echo "BACKGROUND_COLOR=${{ secrets.PRODUCTION_BG_COLOR }}" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Gebruik de action voor deployment naar gh-pages
        with:
          deploy_key: ${{ secrets.GH_TOKEN }}  # Je deploy sleutel (GitHub Token)
          publish_dir: ./  # Publiceer de root directory (of stel hier je public folder in)
          user_name: 'GitHub Actions'
          user_email: 'actions@github.com'
