name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - stage

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Checkout de code van de repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Stap 2: Stel de omgevingsvariabelen in voor de achtergrondkleur
      - name: Set background color environment variable
        run: |
          if [ "${{ github.ref }}" == "refs/heads/stage" ]; then
            echo "STAGE_BG_COLOR=${{ secrets.STAGE_BG_COLOR }}" >> $GITHUB_ENV
          else
            echo "PRODUCTION_BG_COLOR=${{ secrets.PRODUCTION_BG_COLOR }}" >> $GITHUB_ENV
          fi

      # Stap 3: Wijzig de index.html om de achtergrondkleur aan te passen
      - name: Modify background color in index.html
        run: |
          if [ "${{ github.ref }}" == "refs/heads/stage" ]; then
            sed -i 's|<body>|<body style="background-color: ${STAGE_BG_COLOR};">|' ./index.html
          else
            sed -i 's|<body>|<body style="background-color: ${PRODUCTION_BG_COLOR};">|' ./index.html
          fi

      # Stap 4: Deploy naar GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./  # Dit moet het pad zijn waar je index.html bestand zich bevindt
          github_token: ${{ secrets.GITHUB_TOKEN }}